### ISSUE TITLE
missing credits + latest additions

### ISSUE THREAD

**Issue by tobozo** [ElectroMagus/M5-FFT#1]
This project uses derived code from @G6EJD's [great work](https://github.com/G6EJD/ESP32-8-Octave-Audio-Spectrum-Display) but it looks like you forgot to add a couple of links in the credits.

I recently added waveform support and some controls to tweak the settings, you may be interested in the [latest changes](https://github.com/tobozo/ESP32-Audio-Spectrum-Waveform-Display/tree/odroid-go).

**Comment by G6EJD** [comment]
Yes I see both mine and tobozo’s code contributions please add the required credits so we don’t have to go through any take-down procedures and no-one wants to do that. Either that or create your own completely new software design to replace this. Thank you.

**Comment by ElectroMagus** [comment]
My apologies-  I'm on vacation and can add credit when I get back later
this week.

**Comment by ElectroMagus** [comment]
My apologies-  I'm on vacation and can add credit when I get back later
this week.

**Comment by G6EJD** [comment]
OK, we are pleased you have found our code useful but nonetheless the need to recognise the copyright owners does not go away and we look forward to you making the amendments in due course.

**Comment by tobozo** [comment]
bump

**Comment by G6EJD** [comment]
I wonder if he did?

**Comment by tobozo** [comment]
Holidays tend to create amnesy once they're past, so I created this [pull request](https://github.com/ElectroMagus/M5-FFT/pull/2) :-)

@G6EJD on the other hand your repo is missing a License file, which may be encouraging what is happening here.

**Comment by G6EJD** [comment]
I've added a licence now, thanks for the hint. I await a response to the pull request...

**Comment by ElectroMagus** [comment]
Hey-

Sorry.  I've been traveling alot the past few months and this completely
slipped my mind.  I'll add the credits when I get home tonight or first
thing in the morning.

Thanks

**Comment by G6EJD** [comment]
No credits added yet...

**Comment by ElectroMagus** [comment]
Added credit in the README.  I'll add notes in the code once I am able to
get back home (traveling for family issue).

**Comment by tobozo** [comment]
thanks for finding the time to update :-)
